version: "3.9"

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: weather-mcp
    env_file:
      - .env
    ports:
      - "8010:8000"
    networks:
      - agent-network

  streamlit-client:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: weather-streamlit
    env_file:
      - .env
    command: streamlit run src/streamlit_chat.py --server.port=8502 --server.address=0.0.0.0
    depends_on:
      - mcp-server
    ports:
      - "8510:8502"
    networks:
      - agent-network

networks:
  agent-network:
    driver: bridge